sudo: required
dist: xenial

language: python
python:
  - "3.7"

install:
  - pip install numpy
  - pip install scikit-learn
  - pip install opencv-python
  - pip install scipy
script:
  - python3 SVM_main.py

notifications:
  email: false
